### ISSUE TITLE
iOS 7 / ARC Compatible?

### ISSUE THREAD

**Issue by NitWitStudios** [1000Memories/TMQuiltView#18]
Love this library! Want to use it for an app I am building, but can you update it to be more compliant with ARC and iOS 7? Thanks!

**Comment by wtuyp** [comment]
Hey,I just make it support ARC.
https://github.com/wtuyp/TMQuiltView

**Comment by wtuyp** [comment]
ARC version below : ]
https://github.com/wtuyp/TMQuiltView

**Comment by NitWitStudios** [comment]
@wtuyp Awesome!
